version: "3.7"

services:
  mqtt:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "8000:8000"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
     - my-network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment: 
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    depends_on:
      - mqtt
    networks:
      - my-network
  
  socket:
    build:
      context: ./app-socket
      dockerfile: Dockerfile
    environment: 
      - MQTT_HOST=mosquitto
      - MQTT_PORT=8000
    depends_on:
      - mqtt
    networks:
      - my-network
  
#  postgres:
#    image: postgres
#    ports:
#      - '5432:5432'
#    environment:
#      POSTGRES_DB: songpark
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: admin

networks:
    my-network:
