DROP TABLE if exists usr CASCADE;
--;;
DROP TABLE if exists band CASCADE;
--;;
DROP TABLE if exists bandmbr CASCADE;
--;;
DROP TABLE if exists rec CASCADE;
--;;
DROP TABLE if exists rating CASCADE;
--;;
DROP TABLE if exists tp CASCADE;
--;;
DROP TABLE if exists tpownr CASCADE;
--;;
DROP TABLE if exists chat CASCADE;
--;;
DROP TABLE if exists chatmbr CASCADE;
--;;
DROP TABLE if exists msg CASCADE;
--;;
DROP SEQUENCE if exists sid_sequence;

