INSERT INTO fx_key VALUES ('fx__input1__gate_threshold');
--;;
INSERT INTO fx_key VALUES ('fx__input2__gate_threshold');
--;;
INSERT INTO fx_key VALUES ('fx__input1__gate_attack');
--;;
INSERT INTO fx_key VALUES ('fx__input2__gate_attack');
--;;
INSERT INTO fx_key VALUES ('fx__input1__gate_release');
--;;
INSERT INTO fx_key VALUES ('fx__input2__gate_release');
--;;
INSERT INTO fx_key VALUES ('fx__input1__reverb_mix');
--;;
INSERT INTO fx_key VALUES ('fx__input2__reverb_mix');
--;;
INSERT INTO fx_key VALUES ('fx__input1__reverb_damp');
--;;
INSERT INTO fx_key VALUES ('fx__input2__reverb_damp');
--;;
INSERT INTO fx_key VALUES ('fx__input1__reverb_room-size');
--;;
INSERT INTO fx_key VALUES ('fx__input2__reverb_room-size');
--;;
INSERT INTO fx_key VALUES ('fx__input1__amplify_drive');
--;;
INSERT INTO fx_key VALUES ('fx__input2__amplify_drive');
--;;
INSERT INTO fx_key VALUES ('fx__input1__amplify_tone');
--;;
INSERT INTO fx_key VALUES ('fx__input2__amplify_tone');
--;;
INSERT INTO fx_key VALUES ('fx__input1__equalizer_low');
--;;
INSERT INTO fx_key VALUES ('fx__input2__equalizer_low');
--;;
INSERT INTO fx_key VALUES ('fx__input1__equalizer_medium-low');
--;;
INSERT INTO fx_key VALUES ('fx__input2__equalizer_medium-low');
--;;
INSERT INTO fx_key VALUES ('fx__input1__equalizer_medium-high');
--;;
INSERT INTO fx_key VALUES ('fx__input2__equalizer_medium-high');
--;;
INSERT INTO fx_key VALUES ('fx__input1__equalizer_high');
--;;
INSERT INTO fx_key VALUES ('fx__input2__equalizer_high');
--;;
INSERT INTO fx_key VALUES ('fx__input1__echo_delay-time');
--;;
INSERT INTO fx_key VALUES ('fx__input2__echo_delay-time');
--;;
INSERT INTO fx_key VALUES ('fx__input1__echo_level');
--;;
INSERT INTO fx_key VALUES ('fx__input2__echo_level');
--;;
INSERT INTO fx_key VALUES ('fx__input1__compressor_threshold');
--;;
INSERT INTO fx_key VALUES ('fx__input2__compressor_threshold');
--;;
INSERT INTO fx_key VALUES ('fx__input1__compressor_ratio');
--;;
INSERT INTO fx_key VALUES ('fx__input2__compressor_ratio');
--;;
INSERT INTO fx_key VALUES ('fx__input1__compressor_attack');
--;;
INSERT INTO fx_key VALUES ('fx__input2__compressor_attack');
--;;
INSERT INTO fx_key VALUES ('fx__input1__compressor_release');
--;;
INSERT INTO fx_key VALUES ('fx__input2__compressor_release');