DELETE FROM fx_value WHERE fx_key IN ('fx.input1.gate/threshold', 'fx.input2.gate/threshold', 'fx.input1.gate/attack', 'fx.input2.gate/attack', 'fx.input1.gate/release', 'fx.input2.gate/release', 'fx.input1.reverb/mix', 'fx.input2.reverb/mix', 'fx.input1.reverb/damp', 'fx.input2.reverb/damp', 'fx.input1.reverb/room-size', 'fx.input2.reverb/room-size', 'fx.input1.amplify/drive', 'fx.input2.amplify/drive', 'fx.input1.amplify/tone', 'fx.input2.amplify/tone', 'fx.input1.equalizer/low', 'fx.input2.equalizer/low', 'fx.input1.equalizer/medium-low', 'fx.input2.equalizer/medium-low', 'fx.input1.equalizer/medium-high', 'fx.input2.equalizer/medium-high', 'fx.input1.equalizer/high', 'fx.input2.equalizer/high', 'fx.input1.echo/delay-time', 'fx.input2.echo/delay-time', 'fx.input1.echo/level', 'fx.input2.echo/level', 'fx.input1.compressor/threshold', 'fx.input2.compressor/threshold', 'fx.input1.compressor/ratio', 'fx.input2.compressor/ratio', 'fx.input1.compressor/attack', 'fx.input2.compressor/attack', 'fx.input1.compressor/release', 'fx.input2.compressor/release');
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input1.gate/threshold';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input2.gate/threshold';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input1.gate/attack';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input2.gate/attack';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input1.gate/release';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input2.gate/release';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input1.reverb/mix';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input2.reverb/mix';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input1.reverb/damp';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input2.reverb/damp';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input1.reverb/room-size';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input2.reverb/room-size';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input1.amplify/drive';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input2.amplify/drive';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input1.amplify/tone';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input2.amplify/tone';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input1.equalizer/low';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input2.equalizer/low';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input1.equalizer/medium-low';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input2.equalizer/medium-low';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input1.equalizer/medium-high';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input2.equalizer/medium-high';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input1.equalizer/high';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input2.equalizer/high';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input1.echo/delay-time';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input2.echo/delay-time';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input1.echo/level';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input2.echo/level';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input1.compressor/threshold';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input2.compressor/threshold';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input1.compressor/ratio';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input2.compressor/ratio';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input1.compressor/attack';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input2.compressor/attack';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input1.compressor/release';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.input2.compressor/release';