DELETE FROM fx_value WHERE fx_key IN ('fx__input1__gate_threshold', 'fx__input2__gate_threshold', 'fx__input1__gate_attack', 'fx__input2__gate_attack', 'fx__input1__gate_release', 'fx__input2__gate_release', 'fx__input1__reverb_mix', 'fx__input2__reverb_mix', 'fx__input1__reverb_damp', 'fx__input2__reverb_damp', 'fx__input1__reverb_room-size', 'fx__input2__reverb_room-size', 'fx__input1__amplify_drive', 'fx__input2__amplify_drive', 'fx__input1__amplify_tone', 'fx__input2__amplify_tone', 'fx__input1__equalizer_low', 'fx__input2__equalizer_low', 'fx__input1__equalizer_medium-low', 'fx__input2__equalizer_medium-low', 'fx__input1__equalizer_medium-high', 'fx__input2__equalizer_medium-high', 'fx__input1__equalizer_high', 'fx__input2__equalizer_high', 'fx__input1__echo_delay-time', 'fx__input2__echo_delay-time', 'fx__input1__echo_level', 'fx__input2__echo_level', 'fx__input1__compressor_threshold', 'fx__input2__compressor_threshold', 'fx__input1__compressor_ratio', 'fx__input2__compressor_ratio', 'fx__input1__compressor_attack', 'fx__input2__compressor_attack', 'fx__input1__compressor_release', 'fx__input2__compressor_release');
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input1__gate_threshold';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input2__gate_threshold';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input1__gate_attack';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input2__gate_attack';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input1__gate_release';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input2__gate_release';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input1__reverb_mix';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input2__reverb_mix';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input1__reverb_damp';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input2__reverb_damp';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input1__reverb_room-size';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input2__reverb_room-size';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input1__amplify_drive';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input2__amplify_drive';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input1__amplify_tone';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input2__amplify_tone';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input1__equalizer_low';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input2__equalizer_low';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input1__equalizer_medium-low';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input2__equalizer_medium-low';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input1__equalizer_medium-high';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input2__equalizer_medium-high';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input1__equalizer_high';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input2__equalizer_high';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input1__echo_delay-time';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input2__echo_delay-time';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input1__echo_level';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input2__echo_level';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input1__compressor_threshold';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input2__compressor_threshold';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input1__compressor_ratio';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input2__compressor_ratio';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input1__compressor_attack';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input2__compressor_attack';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input1__compressor_release';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx__input2__compressor_release';