INSERT INTO fx_key VALUES ('fx.input1.gate/threshold');
--;;
INSERT INTO fx_key VALUES ('fx.input2.gate/threshold');
--;;
INSERT INTO fx_key VALUES ('fx.input1.gate/attack');
--;;
INSERT INTO fx_key VALUES ('fx.input2.gate/attack');
--;;
INSERT INTO fx_key VALUES ('fx.input1.gate/release');
--;;
INSERT INTO fx_key VALUES ('fx.input2.gate/release');
--;;
INSERT INTO fx_key VALUES ('fx.input1.reverb/mix');
--;;
INSERT INTO fx_key VALUES ('fx.input2.reverb/mix');
--;;
INSERT INTO fx_key VALUES ('fx.input1.reverb/damp');
--;;
INSERT INTO fx_key VALUES ('fx.input2.reverb/damp');
--;;
INSERT INTO fx_key VALUES ('fx.input1.reverb/room-size');
--;;
INSERT INTO fx_key VALUES ('fx.input2.reverb/room-size');
--;;
INSERT INTO fx_key VALUES ('fx.input1.amplify/drive');
--;;
INSERT INTO fx_key VALUES ('fx.input2.amplify/drive');
--;;
INSERT INTO fx_key VALUES ('fx.input1.amplify/tone');
--;;
INSERT INTO fx_key VALUES ('fx.input2.amplify/tone');
--;;
INSERT INTO fx_key VALUES ('fx.input1.equalizer/low');
--;;
INSERT INTO fx_key VALUES ('fx.input2.equalizer/low');
--;;
INSERT INTO fx_key VALUES ('fx.input1.equalizer/medium-low');
--;;
INSERT INTO fx_key VALUES ('fx.input2.equalizer/medium-low');
--;;
INSERT INTO fx_key VALUES ('fx.input1.equalizer/medium-high');
--;;
INSERT INTO fx_key VALUES ('fx.input2.equalizer/medium-high');
--;;
INSERT INTO fx_key VALUES ('fx.input1.equalizer/high');
--;;
INSERT INTO fx_key VALUES ('fx.input2.equalizer/high');
--;;
INSERT INTO fx_key VALUES ('fx.input1.echo/delay-time');
--;;
INSERT INTO fx_key VALUES ('fx.input2.echo/delay-time');
--;;
INSERT INTO fx_key VALUES ('fx.input1.echo/level');
--;;
INSERT INTO fx_key VALUES ('fx.input2.echo/level');
--;;
INSERT INTO fx_key VALUES ('fx.input1.compressor/threshold');
--;;
INSERT INTO fx_key VALUES ('fx.input2.compressor/threshold');
--;;
INSERT INTO fx_key VALUES ('fx.input1.compressor/ratio');
--;;
INSERT INTO fx_key VALUES ('fx.input2.compressor/ratio');
--;;
INSERT INTO fx_key VALUES ('fx.input1.compressor/attack');
--;;
INSERT INTO fx_key VALUES ('fx.input2.compressor/attack');
--;;
INSERT INTO fx_key VALUES ('fx.input1.compressor/release');
--;;
INSERT INTO fx_key VALUES ('fx.input2.compressor/release');