DELETE FROM fx_value WHERE fx_key IN ('fx.gate/threshold', 'fx.gate/attack', 'fx.gate/release', 'fx.reverb/mix', 'fx.reverb/damp', 'fx.reverb/room-size', 'fx.amplify/drive', 'fx.amplify/tone', 'fx.equalizer/low', 'fx.equalizer/medium-low', 'fx.equalizer/medium-high', 'fx.equalizer/high', 'fx.echo/delay-time', 'fx.echo/level', 'fx.compressor/threshold', 'fx.compressor/ratio', 'fx.compressor/attack', 'fx.compressor/release');
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.gate/threshold';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.gate/attack';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.gate/release';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.reverb/mix';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.reverb/damp';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.reverb/room-size';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.amplify/drive';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.amplify/tone';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.equalizer/low';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.equalizer/medium-low';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.equalizer/medium-high';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.equalizer/high';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.echo/delay-time';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.echo/level';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.compressor/threshold';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.compressor/ratio';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.compressor/attack';
--;;
DELETE FROM fx_key VALUES WHERE id = 'fx.compressor/release';