INSERT INTO fx_key VALUES ('fx.gate/threshold');
--;;
INSERT INTO fx_key VALUES ('fx.gate/attack');
--;;
INSERT INTO fx_key VALUES ('fx.gate/release');
--;;
INSERT INTO fx_key VALUES ('fx.reverb/mix');
--;;
INSERT INTO fx_key VALUES ('fx.reverb/damp');
--;;
INSERT INTO fx_key VALUES ('fx.reverb/room-size');
--;;
INSERT INTO fx_key VALUES ('fx.amplify/drive');
--;;
INSERT INTO fx_key VALUES ('fx.amplify/tone');
--;;
INSERT INTO fx_key VALUES ('fx.equalizer/low');
--;;
INSERT INTO fx_key VALUES ('fx.equalizer/medium-low');
--;;
INSERT INTO fx_key VALUES ('fx.equalizer/medium-high');
--;;
INSERT INTO fx_key VALUES ('fx.equalizer/high');
--;;
INSERT INTO fx_key VALUES ('fx.echo/delay-time');
--;;
INSERT INTO fx_key VALUES ('fx.echo/level');
--;;
INSERT INTO fx_key VALUES ('fx.compressor/threshold');
--;;
INSERT INTO fx_key VALUES ('fx.compressor/ratio');
--;;
INSERT INTO fx_key VALUES ('fx.compressor/attack');
--;;
INSERT INTO fx_key VALUES ('fx.compressor/release');